EFFECT_TYPE_CANNON = 1
EFFECT_TYPE_RIFLE = 2
EFFECT_TYPE_CRASH = 3
EFFECT_TYPE_BOMB = 4

GAME_STATE_BUILDING = 1
GAME_STATE_FIGHT = 2
GAME_STATE_PAUSE = 3

AW_DAMAGE_TYPE_SPLASH = 1
AW_DAMAGE_TYPE_HIT = 2
